'use client';
import {useState} from 'react';
import PartArt from '@/components/PartArt';
import {adc} from '@/lib/learning-models';
import {Slider,Choices,Metrics,Note,LabFrame,type LabProps} from './Controls';
const BOARDS = {
  esp32:{name:'ESP32-DevKitC V4',chip:'ESP32-WROOM-32',voltage:'3.3 V',wireless:'Wi-Fi · Bluetooth',pins:[['3V3','센서에 3.3 V 전원을 공급하는 핀이에요.'],['GND','전압을 비교하는 공통 기준점이에요.'],['GPIO21 · SDA','이 예시에서 I²C 데이터를 주고받아요. 핀은 소프트웨어에서 설정해요.'],['GPIO22 · SCL','이 예시에서 I²C 통신 타이밍을 맞춰요.'],['GPIO34 · ADC','입력 전용 ADC 핀이에요. 출력이나 내부 풀업·풀다운을 사용할 수 없어요.'],['GPIO18 · PWM','소프트웨어 설정으로 PWM 출력을 만들 수 있어요.']]},
  uno:{name:'Arduino UNO R3',chip:'ATmega328P',voltage:'5 V',wireless:'기본 보드에 무선 기능 없음',pins:[['5V','5 V 전원 핀이에요. ESP32 센서와 연결할 때 전압 호환을 확인해요.'],['GND','다른 장치와 전압을 비교하는 기준점이에요.'],['A4 · SDA','UNO R3의 I²C 데이터 핀이에요.'],['A5 · SCL','UNO R3의 I²C 클록 핀이에요.'],['A0 · ADC','기본 10비트 ADC로 아날로그 입력을 읽어요.'],['D9 · PWM','PWM 출력이 가능한 핀 중 하나예요. 일반적인 analogWrite 값은 0–255예요.']]},
  pico:{name:'Raspberry Pi Pico 1',chip:'RP2040',voltage:'3.3 V',wireless:'기본 Pico에는 무선 기능 없음',pins:[['3V3(OUT)','3.3 V 전원 출력이에요. GPIO에 5 V를 넣지 않아요.'],['GND','전압의 기준점이에요.'],['GP0 · SDA','I²C0 데이터로 설정할 수 있는 핀이에요.'],['GP1 · SCL','I²C0 클록으로 설정할 수 있는 핀이에요.'],['GP26 · ADC','12비트 ADC 입력으로 사용할 수 있어요.'],['GP15 · PWM','PWM 출력으로 설정할 수 있는 핀이에요.']]},
};
export function BoardLab({onPass}:LabProps){
 const [board,setBoard]=useState<keyof typeof BOARDS>('esp32'),[pin,setPin]=useState(0);const b=BOARDS[board];
 return <LabFrame visual={<><div className="board-scene"><PartArt kind="esp32"/><div><small>기능 탐색 · 실제 핀 배치 아님</small><h3>{b.name}</h3><p>{b.chip}</p></div></div><div className="pin-grid">{b.pins.map((p,i)=><button key={p[0]} aria-pressed={pin===i} onClick={()=>{setPin(i);if(i===4)onPass();}}>{p[0]}</button>)}</div><div className="pin-description" role="status"><b>{b.pins[pin][0]}</b><p>{b.pins[pin][1]}</p></div></>}>
 <Choices label="보드 선택" value={board} options={[{value:'esp32',label:'ESP32'},{value:'uno',label:'UNO R3'},{value:'pico',label:'Pico 1'}]} onChange={v=>{setBoard(v);setPin(0);}}/>
 <Metrics items={[{label:'GPIO 신호 전압',value:b.voltage}]}/><Note>{b.wireless}</Note><Note warning>사진은 ESP32 형태 참고 그림이에요. UNO와 Pico를 선택해도 실제 보드 사진으로 바뀌는 것은 아니에요. 정확한 물리적 핀 위치는 제조사 자료를 확인해요.</Note>
 </LabFrame>;
}
export function PwmLab({onPass}:LabProps){
 const [duty,setDuty]=useState(50),[frequency,setFrequency]=useState(500),[playing,setPlaying]=useState(true);const period=1000/frequency;
 const wave=Array.from({length:4},(_,i)=>{const x=65+i*112.5,w=112.5*duty/100;return duty===0?`M${x}185h112.5`:duty===100?`M${x}65h112.5`:`M${x}185V65h${w}V185H${x+112.5}`;}).join(' ');
 return <LabFrame visual={<><div className="pwm-heading"><span className="virtual-led" style={{opacity:.12+duty/100*.88}} aria-label={`LED 평균 출력 ${duty}%`}/><div><b>켜짐 {duty}% · 꺼짐 {100-duty}%</b><p>빠른 ON / OFF를 평균 밝기로 느껴요.</p></div></div><svg viewBox="0 0 560 260" className="learn-diagram" role="img" aria-label={`PWM 듀티 ${duty}퍼센트, 주파수 ${frequency}헤르츠, 네 주기의 파형`}><path d="M65 35v170h450" className="plot-axis"/><path d="M65 65h450M65 185h450" className="plot-grid"/><text x="8" y="70">3.3 V</text><text x="20" y="190">0 V</text><path d={wave} className="plot-current"/><path d={`M65 ${185-120*duty/100}h450`} className="plot-average"/>{[0,1,2,3,4].map(i=><text key={i} x={65+i*112.5} y="230" textAnchor="middle">{(i*period).toFixed(1)}</text>)}<text x="500" y="254">ms</text>{playing&&<path d="M65 35v170" className="time-cursor"/>}</svg><Metrics items={[{label:'한 주기',value:period.toFixed(2),unit:'ms'},{label:'HIGH 시간',value:(period*duty/100).toFixed(3),unit:'ms'},{label:'평균 전압',value:(3.3*duty/100).toFixed(3),unit:'V'}]}/></>}>
 <Slider label="듀티 비율" value={duty} min={0} max={100} unit="%" onChange={v=>{setDuty(v);if(v===25)onPass();}}/><Slider label="반복 주파수" value={frequency} min={100} max={2000} step={100} unit="Hz" onChange={setFrequency}/><button className="learn-secondary" aria-pressed={playing} onClick={()=>setPlaying(!playing)}>{playing?'시간 표시 멈추기':'시간 표시 움직이기'}</button><Note>점선은 평균 전압이에요. 주파수를 바꿔도 듀티가 같으면 평균 전압은 같아요. 이동선은 시간을 보여주는 느린 안내 표시예요.</Note>
 </LabFrame>;
}
export function AdcLab({onPass}:LabProps){
 const [v,setV]=useState(1.65),[bits,setBits]=useState('4');const a=adc(v,+bits),n=Math.min(a.levels,32);const path=Array.from({length:n},(_,i)=>`M${65+i*450/n} ${210-i*160/(n-1)}h${450/n}v${i===n-1?0:-160/(n-1)}`).join(' ');
 return <LabFrame visual={<><svg viewBox="0 0 560 290" className="learn-diagram" role="img" aria-label={`입력 ${v}볼트를 ${bits}비트 ADC로 변환한 코드 ${a.code}`}><path d="M65 30v200h450" className="plot-axis"/><path d="m65 210 450-160" className="plot-average"/><path d={path} className="plot-current"/><circle cx={65+v/3.3*450} cy={210-a.code/(a.levels-1)*160} r="8" fill="var(--learn-amber)" stroke="var(--learn-ink)" strokeWidth="2"/><text x="10" y="53">{a.levels-1}</text><text x="35" y="215">0</text><text x="65" y="253">0 V</text><text x="478" y="253">3.3 V</text><text x="280" y="285" textAnchor="middle">{a.levels>32?'계단 모양은 32칸으로 축약 · 코드 계산은 선택한 비트 수 그대로':'초록 계단: 디지털 코드 · 점선: 연속 입력'}</text></svg><Metrics items={[{label:'변환 코드',value:String(a.code)},{label:'구분하는 칸',value:a.levels.toLocaleString('ko-KR'),unit:'개'},{label:'한 칸 크기',value:(a.step*1000).toFixed(3),unit:'mV'}]}/></>}>
 <Slider label="입력 전압" value={v} min={0} max={3.3} step={.01} unit="V" onChange={setV}/><Choices label="ADC 해상도" value={bits} options={['4','8','10','12'].map(value=>({value,label:`${value}비트`}))} onChange={value=>{setBits(value);if(value==='12')onPass();}}/><Note>지금 코드는 약 {a.low.toFixed(4)} V부터 {a.high.toFixed(4)} V 사이의 한 칸을 나타내요. 끝값 3.3 V는 마지막 코드로 제한돼요.</Note>
 </LabFrame>;
}
export function I2cLab({onPass}:LabProps){
 const expected=['3V3','GND','GPIO22','GPIO21'],names=['VCC','GND','SCL','SDA'];
 const [links,setLinks]=useState(expected),[extra,setExtra]=useState('none'),[message,setMessage]=useState('배선을 확인하고 가상 통신 버튼을 눌러 봐요.'),[ok,setOk]=useState(false);
 const colors=['#b64c38','#36493f','#376d9e','#2f815c'];
 function check(){if(links.includes('5V')){setOk(false);setMessage('STOP · 이 실험에서는 센서를 3.3 V로 연결해요. 5 V 선택을 바꿔 주세요.');return;}if(links.some((p,i)=>p!==expected[i])){setOk(false);setMessage('연결을 다시 확인해요. VCC→3V3, GND→GND, SCL→GPIO22, SDA→GPIO21이에요.');return;}if(extra==='0x40'){setOk(false);setMessage('주소 충돌 · INA219 두 개가 모두 0x40이에요. 추가 INA219의 주소를 다르게 설정해야 해요.');return;}setOk(true);setMessage(`통신 성공 · BH1750 0x23, INA219 0x40${extra==='0x41'?', 추가 INA219 0x41':''}`);onPass();}
 return <LabFrame visual={<><svg viewBox="0 0 560 320" className="learn-diagram" role="img" aria-label="ESP32와 두 I2C 센서의 논리 연결도"><rect x="18" y="46" width="175" height="220" rx="14" fill="#e1eae0"/><text x="105" y="80" textAnchor="middle">ESP32</text><rect x="360" y="40" width="184" height="102" rx="12" fill="#fff" stroke="#bdcdbd"/><rect x="360" y="188" width="184" height="102" rx="12" fill="#fff" stroke="#bdcdbd"/><text x="455" y="65" textAnchor="middle">INA219 · 0x40</text><text x="455" y="213" textAnchor="middle">BH1750 · 0x23</text>{names.map((name,i)=><g key={name}><text x="36" y={116+i*38}>{links[i]}</text><path d={`M170 ${111+i*38}H${240+i*22}V${90+i*12}H370M${240+i*22} ${111+i*38}V${235+i*12}H370`} stroke={colors[i]} fill="none" strokeWidth="2.5"/><circle cx={240+i*22} cy={111+i*38} r="3" fill={colors[i]}/><text x="385" y={95+i*12} fontSize="11">{name}</text><text x="385" y={240+i*12} fontSize="11">{name}</text></g>)}<text x="280" y="318" textAnchor="middle">전원과 GND도 공유 · SDA / SCL은 대화선</text></svg><Note warning={!ok}>{message}</Note></>}>
 <div className="i2c-connections">{names.map((name,i)=><label className="learn-select" key={name}>센서 {name}<select value={links[i]} onChange={e=>{setLinks(links.map((v,j)=>i===j?e.target.value:v));setOk(false);setMessage('배선이 바뀌었어요. 다시 가상 통신을 확인해요.');}}>{[...expected,'5V'].map(value=><option key={value}>{value}</option>)}</select></label>)}</div>
 <label className="learn-select">추가 INA219 주소<select value={extra} onChange={e=>{setExtra(e.target.value);setOk(false);setMessage('주소 설정이 바뀌었어요. 다시 확인해요.');}}><option value="none">추가 센서 없음</option><option value="0x40">0x40 · 기본 주소</option><option value="0x41">0x41 · 주소 변경</option></select></label>
 <button className="learn-primary" onClick={check}>가상 통신 확인</button><Note>0x41은 추가 INA219의 주소 설정을 바꾼 상황이에요. 실제로는 모듈의 주소 점퍼를 확인해야 해요.</Note>
 </LabFrame>;
}
