'use client';
import {useState} from 'react';
import PartArt from '@/components/PartArt';
import {solar,energy} from '@/lib/learning-models';
import {Slider,Metrics,Note,LabFrame,type LabProps} from './Controls';
export function SolarLab({onPass}:LabProps){
 const [light,setLight]=useState(800),[angle,setAngle]=useState(0),[temperature,setTemperature]=useState(25),[load,setLoad]=useState(40);
 const s=solar(light,angle,temperature,load),x=(v:number)=>55+v/12*445,yi=(i:number)=>243-i/.7*205,yp=(p:number)=>243-p/6*205;
 const iv=s.points.map((p,i)=>`${i?'L':'M'}${x(p.v).toFixed(2)} ${yi(p.i).toFixed(2)}`).join(' '),pv=s.points.map((p,i)=>`${i?'L':'M'}${x(p.v).toFixed(2)} ${yp(p.p).toFixed(2)}`).join(' ');
 return <LabFrame visual={<><div className="solar-scene"><div className="solar-sun" style={{opacity:.15+light/1000*.85}}>☀</div><div style={{transform:`perspective(500px) rotateY(${angle*.75}deg)`}}><PartArt kind="panel"/></div><p>光 → 電<br/><span>개념 모형</span></p></div><div className="plot-legend"><span>━ 전류 I–V</span><span>┄ 전력 P–V</span><span>● 현재 부하</span></div><svg className="learn-diagram solar-chart" viewBox="0 0 560 302" role="img" aria-label={`현재 전압 ${s.v.toFixed(2)}볼트, 전력 ${s.power.toFixed(2)}와트. 교육용 I-V와 P-V 곡선`}>
 {[0,1,2,3].map(i=><g key={i}><path d={`M55 ${243-i*205/3}h445`} className="plot-grid"/><text x="42" y={248-i*205/3} textAnchor="end">{(i*.7/3).toFixed(2)}</text><text x="512" y={248-i*205/3}>{i*2}</text></g>)}<path d="M55 32v211h445V32" className="plot-axis"/>{[0,3,6,9,12].map(v=><text key={v} x={x(v)} y="268" textAnchor="middle">{v}</text>)}<text x="55" y="19">전류 A</text><text x="460" y="19">전력 W</text><text x="280" y="295" textAnchor="middle">전압 V</text><path d={iv} className="plot-current"/><path d={pv} className="plot-power"/>{s.mppP>0&&<><path d={`M${x(s.v)} 32V243`} className="plot-average"/><circle cx={x(s.v)} cy={yp(s.power)} r="7" fill="var(--learn-amber)" stroke="#fff" strokeWidth="2"/><circle cx={x(s.mppV)} cy={yp(s.mppP)} r="5" fill="var(--learn-green)"/><text x={x(s.mppV)-10} y={yp(s.mppP)-12} textAnchor="end">MPP</text></>}</svg>
 <Metrics items={[{label:'현재 전압',value:s.v.toFixed(2),unit:'V'},{label:'현재 전류',value:(s.current*1000).toFixed(1),unit:'mA'},{label:'현재 전력',value:s.power.toFixed(3),unit:'W'}]}/><div className="mpp-comparison"><span>최대 {s.mppP.toFixed(3)} W 중 <b>{s.efficiency.toFixed(1)}%</b></span><div role="progressbar" aria-label="최대전력 대비 현재 전력" aria-valuenow={Math.round(s.efficiency)} aria-valuemin={0} aria-valuemax={100}><i style={{width:`${Math.min(100,s.efficiency)}%`}}/></div></div></>}>
 <Slider label="빛의 세기" value={light} min={0} max={1000} step={50} unit="W/m²" onChange={setLight}/><Slider label="정면에서 벗어난 각도" value={angle} min={0} max={90} step={5} unit="°" onChange={setAngle}/><Slider label="패널 온도" value={temperature} min={0} max={75} step={5} unit="°C" onChange={setTemperature}/><Slider label="부하 저항" value={load} min={1} max={Math.max(200,Math.ceil(s.optimalR/100)*100,Math.ceil(load/100)*100)} step={.1} unit="Ω" onChange={setLoad}/>
 <button className="learn-primary" disabled={s.mppP===0} onClick={()=>{setLoad(Math.round(s.optimalR*10)/10);onPass();}}>최대전력점 근처로 맞추기</button><Note>{s.mppP===0?'지금은 직접 들어오는 빛이 없어요. 빛을 늘리거나 패널을 정면으로 돌려 보세요.':'저항이 너무 작거나 커도 전력이 줄어요. 자동 맞추기는 이 모형의 최적 부하를 계산하는 기능이지 실제 MPPT 제어기가 아니에요.'}</Note>
 </LabFrame>;
}
export function EnergyLab({onPass}:LabProps){
 const [panel,setPanel]=useState(5),[sun,setSun]=useState(3),[efficiency,setEfficiency]=useState(70),[load,setLoad]=useState(1),[hours,setHours]=useState(12);
 const e=energy(panel,sun,efficiency,load,hours),max=Math.max(e.produced,e.consumed,1);
 return <LabFrame visual={<><div className="energy-art"><PartArt kind="panel"/><span>W × 시간 = Wh</span><PartArt kind="record"/></div><div className="energy-bars"><div><label>하루 예상 발전량 <b>{e.produced.toFixed(2)} Wh</b></label><div><i style={{width:`${e.produced/max*100}%`}}/></div></div><div><label>하루 소비량 <b>{e.consumed.toFixed(2)} Wh</b></label><div><i style={{width:`${e.consumed/max*100}%`}}/></div></div></div><div className={`energy-balance${e.balance>=0?' positive':''}`} role="status"><small>{e.balance>=0?'에너지 예산에 여유가 있어요':'사용량이 발전량보다 많아요'}</small><strong>{e.balance>0?'+':''}{e.balance.toFixed(2)} <span>Wh / 일</span></strong></div><p className="learn-equation">{panel} W × {sun} h × {efficiency}% = {e.produced.toFixed(2)} Wh</p></>}>
 <Slider label="패널 정격 전력" value={panel} min={1} max={20} unit="W" onChange={setPanel}/><Slider label="등가 최대일조시간" value={sun} min={0} max={8} step={.5} unit="h" onChange={setSun}/><Slider label="시스템 효율" value={efficiency} min={10} max={100} step={5} unit="%" onChange={setEfficiency}/><Slider label="장치 소비 전력" value={load} min={.1} max={5} step={.1} unit="W" onChange={setLoad}/><Slider label="하루 사용 시간" value={hours} min={0} max={24} unit="h" onChange={v=>{setHours(v);if(energy(panel,sun,efficiency,load,v).balance>=0)onPass();}}/>
 <Note warning>하루 총량이 충분해도 밤에 바로 쓸 수 있다는 뜻은 아니에요. 발전 시간과 사용 시간, 저장 손실을 별도로 고려해야 해요. 여기서는 배터리 충전을 실습하지 않아요.</Note>
 </LabFrame>;
}
